### PR TITLE
change version.oh to h_version.txt, update getinfo for v3 fixes

### PR DESCRIPTION
**Pull request by strawbberrys**
this is due to synapse 3.0 having a whitelist on file types. the name isn't very good but can be changed.

### CODE REVIEW

**Comment by Upbolt** [comment]
I remember Louka being aware of esoteric file extensions and speaking on the matter so I don't know why they would add a whitelist, but if this is the case, I'll talk to 3ds and Louka about whitelisting the "oh" extension. Until then though, I'll leave this open so you can remove the name changes in your commits & only leave the getinfo fix

**Comment by Upbolt** [comment]
oops lol

**Comment by strawbberrys** [comment]
this probably will never be changed. i feel like it would be easier to change the file to .txt instead of trying to get the .oh file whitelisted. not only that but having this fix implemented would allow people to use hydroxide on v3 instead of having to use a fork.

**Comment by Upbolt** [comment]
does synapse v3 have any globals we can use instead of calling identifyexecutor? i don't think a majority of freesploits have that func

**Comment by strawbberrys** [comment]
I don't think it has anything besides its new custom functions. I can update this to make sure that identifyexecutor exists and if so check.

**Comment by Upbolt** [comment]
synapse is gone

**Pull request closed without merging**
