### PR TITLE
fix hydroxide erroring without playerscripts

### PR DESCRIPTION
**Pull request by Iaying6564**
idk what this code even is but its pasted & detected!!

### CODE REVIEW

**Review by strawbberrys — CHANGES_REQUESTED** [review]
i don't see this module being used throughout the rest of the hydroxide source. maybe deleting this module entirely would work better?

**Comment by Upbolt** [comment]
waiting for response on #69 before i merge this

**Comment by strawbberrys** [comment]
i wouldn't merge because a lot of the changes still have Iaying6564 as the url instead of Upbolt

**Comment by Upbolt** [comment]
old

**Pull request closed without merging**
